version: '3.7'

services: 
  client:
    image: scheduler_client:latest
    build:
      context: client
      dockerfile: Dockerfile
  server:
    image: scheduler_server:latest
    build:
      context: server
      dockerfile: Dockerfile
  histogram:
    image: scheduler_histogram:latest
    build:
      context: histogram
      dockerfile: Dockerfile
  