version: '3.7'

services:
  client:
    ports: 
    - 8081:8080
    environment:
    - REST_URL=http://server:8080/
  server:
    stdin_open: true
    tty: true
    ports: 
    - 8080:8080
  histogram:
    ports:
      - 3000:3000
    environment:
    - REST_URL=http://server:8080/
    volumes:
      - ./histogram/src:/app/src